name: Deploy Multiple Slidev Pages

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        slidev_folder: [lecture1, lecture2]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup @antfu/ni
        run: npm i -g @antfu/ni

      - name: Install dependencies (${{ matrix.slidev_folder }})
        timeout-minutes: 10
        run: |
          cd ${{ matrix.slidev_folder }}
          nci

      - name: Build (${{ matrix.slidev_folder }})
        run: |
          cd ${{ matrix.slidev_folder }}
          nr build --base /${{ github.event.repository.name }}/${{ matrix.slidev_folder }}/

      - name: Upload artifact for ${{ matrix.slidev_folder }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.slidev_folder }}
          path: ${{ matrix.slidev_folder }}/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          folder: dist

